### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [justdoit89/prj-rev-bwfs-dasmoto#3]
(Simplify) Alternatively, you can specify shared properties for multiple elements by including all the selectors separated by commas:

```css
h1, h2 {
  font-family: Helvetica;
  font-weight: bold;
}
```

https://github.com/justdoit89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20%20Arts%20and%20Crafts/Resources/style.css#L1-L14
